image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build
  - name: Run
    command: dotnet run

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - ckolkman.vscode-postgres
    - dsznajder.es7-react-js-snippets
    - formulahendry.auto-close-tag
    - github.vscode-github-actions
    - mongodb.mongodb-vscode
    - ms-azuretools.vscode-docker
    - ms-dotnettools.csdevkit
    - ms-dotnettools.csharp
    - ms-dotnettools.vscode-dotnet-runtime
    - ms-dotnettools.vscodeintellicode-csharp
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - patcx.vscode-nuget-gallery
    - PKief.material-icon-theme
    - redhat.vscode-yaml
    - zxh404.vscode-proto3
